"""empty message

Revision ID: 3b6fdda5cfcd
Revises: 6b54ec6e0004
Create Date: 2016-04-24 07:26:51.737985

"""

# revision identifiers, used by Alembic.
revision = '3b6fdda5cfcd'
down_revision = '6b54ec6e0004'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('image_filename', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'image_filename')
    ### end Alembic commands ###
