"""empty message

Revision ID: 49d16f4082cd
Revises: 52137c40690c
Create Date: 2016-04-24 09:34:34.153606

"""

# revision identifiers, used by Alembic.
revision = '49d16f4082cd'
down_revision = '52137c40690c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('is_active', sa.String(length=255), nullable=True))
    op.drop_column('member', u'active')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column(u'active', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('member', 'is_active')
    ### end Alembic commands ###
